### ISSUE TITLE
Darkmode

### ISSUE THREAD

**Issue by ladydarkja** [janaRicarda/emotion-tracker#16]
## Value proposition
As a user
I want to have the possibility to switch between light and dark mode
In order to use my preferred colorscheme
## Description

![Image](https://github.com/janaRicarda/emotion-tracker/assets/115214197/e700bb27-6e77-4f66-afb6-e7ec3793a3cf)

## Acceptance criteria
- [ ] Toggle button to switch between light and dark theme

## Tasks
- [ ] create and switch to branch feature/darkmode
- [ ] import `ThemeProvider`
- [ ] create a component `Theme.js`
- [ ] create a lighttheme and a darktheme and add it to the root element
- [ ] write logic for the toggle function
- [ ] add the logic to the button
