### ISSUE TITLE
layout

### ISSUE THREAD

**Issue by janaRicarda** [janaRicarda/emotion-tracker#18]
## Value proposition
As a user
I want to have a visual feedback while navigating through in the app
In order to always know where I am and have orientation
## Description

![Image](https://github.com/janaRicarda/emotion-tracker/assets/152087816/edf0956a-8da9-49eb-bff3-a672567649db)

## Acceptance criteria
- [ ] The Layout is displayed on every page
- [ ] The Layout exists of a header and a footer
- [ ] The header displays the App name
- [ ] The footer displays the navigation menu

## Tasks
- [ ] create and switch to the branch `feature/layout`
- [ ] create the component `Header`, which renders the Appname
- [ ] `Header`gets position: fixed and top: 0
- [ ] create the component `Navigation`, which renders a navigation menu, consisting of `Links`
- [ ] `Navigation` gets position: fixed and bottom: 0
- [ ] create the component `Layout`, give it the prop `{children}` and render `Header`, `children` and 
    `Navigation` in it
- [ ] render `Layout` in `_app.js` and wrapp it around the `Component`component.
- [ ] Delete all the existing navigation links in the app
