### ISSUE TITLE
create-emotion-entry

### ISSUE THREAD

**Issue by janaRicarda** [janaRicarda/emotion-tracker#4]
# Create Emotion Entry

## Value Proposition

**As a** user

**I want to** record more details of my emotions

**so that** I can write down  my emotional experiences over time.

## Description

![Image](https://github.com/janaRicarda/emotion-tracker/assets/152093131/8c6fa30c-17c2-40a7-ad28-1d34e3577096)

## Acceptance criteria
- After setting their tension-level, the user can "save"(button). After clicking "save" two buttons show up to give options for either go to go "Back" or to "Add more details". 
- On "Back" the tension-level is reset and the user can make a new tension entry
- On "Add more details" the user can choose one of the 7 Basic Emotions to classify their main inner feeling on click. This opens a new form.
- A clear headline like: "Record your [chosen basic emotion, e.g. "Joy"]", is displayed indicating the form's purpose.
- The form includes fields with corresponding labels for each input:
  - Date and time: This Field is automatically set to the current date and time.
  - Selected Sub-Emotion: Required field to select an emotion that includes some options (e.g contentment, pride, relief, excitement, ecstasy)
  - Emotion intensity: Required field (e.g. a slider) to rate the emotion on a scale from 1 to 100.
  - Association category: inputfield (e.g. a slider) to select between "unpleasant", "neutral" and "pleasant".
  - Reason/Trigger of the emotion: Optional text input
  - Additional notes: Optional text input
- A clearly labeled button is displayed to submit the form.
- Upon submission, the new emotion record is added to the Emotion Records list.
- Form submission with any empty mandatory fields is blocked, and clear validation messages indicate the fields that need 
  completion.
- At the end of the Page, the user can navigate back to main page via "Back to Tension Entry".

## Tasks

- [ ] Create and switch to the feature branch `feature/create-emotion-entry`
- [ ]  Create a component called `EmotionForm`, including the following:
       - `input type="date"`, automatically set to current date
       - `select` to implement a drop down menu including the choosable subemotions, `required`
       - two `input type="range"`sliders, one to rate the intensity of the felt emotion and one to categorize into unpleasant, neutral or pleasant, `required`
       - all `required` `input fields` are marked with an * in the label
       - two `input type="text"`with the `labels` "trigger" and "additional notes". Code them to not be required.
       - a `submit` button that updates the `useLocalStorageState` with the new `formData` on submit. Use `router.push` to update  and lead to `pages/emotion-records.js`.
- [ ] Add `h1` and interpolate the chosen basic Emotion into the `title` "Record your [...]".
- [ ] Add `Link` "Back to Tension Entry" to navigate back to `/pages/index.js`.
- [ ] Create new page `page/create/[slug]/index.js` and reuse the component `EmotionList` on that page
- [ ] On `pages/index.js` add two `Link`s  "Back" and "Add more details" that are conditonaly rendered after "saving" the tension entry
- "Back" resets the create tension `form`
- "Add more details" links to the `page/create/[slug]/index.js`
- [ ] Create new page `pages/create/form.js`, render `EmotionForm` there and update `EmotionList` so that a cick on the chosen basic emotion links to `pages/create/form.js`
- [ ] Update `EmotionRecordsList` component to also render the new information from the `useLocalStorageState`: `emotion`, `sub-emotion`, `intensity-level`, `associating-category`, `Trigger` and `Notes`. Optional key-value pairs  are not displayed if empty.
- [ ] Add minimal styling accordingly.

**Comment by FelineHuhn** [comment]
Great work team 🤩 Although it is a large user story, you have managed to formulate and structure everything in a way that is easy to understand! 

Looking at your wireframes, I had the idea whether it might be good for the user experience if the required input fields were marked as required, e.g. with an * in the label, or what do you think?

I have noticed that your file names may not be completely consistent (you mentioned `pages/emotion-records.js`, `pages/create/index.js`). Is that the plan?

And I'm still thinking about one task: "Update EmotionList, so that the corresponding Link of the chosen basic emotion displays EmotionForm instead of EmotionDetail." -> The `EmotionDetails` component is rendered on the page `/pages/emotions/[slug]/index.js` in the feature for emotion details. Now you write "displays `EmotionForm` instead of `EmotionDetails`. On which page should this take place? Also from a semantic point of view, I am surprised to find the `EmotionList` on the `/pages/create/index.js` page and not the `CreateForm`. I don't have a perfect solution for this myself right now, but have you thought about it again?
