### ISSUE TITLE
Tension Chart to pdf

### ISSUE THREAD

**Issue by janaRicarda** [janaRicarda/emotion-tracker#41]
## Value proposition
As a user
I want to download or print my tension charts
In order to discuss with my Therapeut
## Description
- Scribble / design or text
- Precise, no unnecessary information
## Acceptance criteria
- [ ] The user can choose the time interval
- [ ] Downloadlink
- [ ] What is the text of an alert?
## Tasks
- [ ] List the tasks that need to be performed within the dev team
