### ISSUE TITLE
Emotionwheel

### ISSUE THREAD

**Issue by janaRicarda** [janaRicarda/emotion-tracker#45]
## Value proposition
As a user
I want to see the emotions as a wheel
In order to avoid any hierarchy given by a top-down list
## Description

![Image](https://github.com/janaRicarda/emotion-tracker/assets/152087816/0838e5f5-3c1c-4a7d-bfd8-f50219c8a48c)

## Acceptance criteria
- [ ] the emotionList Shows up as circle 
- [ ] every Emotion fills a "piece of cake"
- [ ] the names of the emotions remain links
- [ ] by scrolling on the Wheel, the wheel rotates 
## Tasks
- [ ] switch to branch feature/emotionwheel
- [ ] adapt styled component of `emotionList`to be a circle
- [ ] adjust `listItems` to fit in the circle
- [ ] add logic to make the `emotionList` rotatable by scrolling
