### ISSUE TITLE
Darkmode improvement

### ISSUE THREAD

**Issue by janaRicarda** [janaRicarda/emotion-tracker#51]
## Value proposition
As a user
I want to have my preferred mode by opening the app
In order to avoid setting the mode by myself
## Description
- Scribble / design or text
- Precise, no unnecessary information
## Acceptance criteria
- [ ] When the user has darkmode as its preferred mode, the app opens in darkmode
- [ ] If he has no settings, the app opens in lightmode
- [ ] The togglebutton remains

## Tasks
- [ ] create and switch to branch feature/darkmode-improvement
- [ ] add logic to consider the users settings
- [ ] add styling to improve the darkmode
