### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by janaRicarda** [janaRicarda/emotion-tracker#65]
## Value proposition
As a user
I want to use the app in any device
so that I can record my emotions everywhere I want
## Description
- Scribble / design or text
- Precise, no unnecessary information
## Acceptance criteria
- [ ] The content and layout works fine on every screen size

## Tasks
- [ ] Create and switch to branch feature/responsiveness
- [ ] add mediaqueries for different devices
- [ ] adjust styling accordingly to the different devices
