### ISSUE TITLE
general refinement

### ISSUE THREAD

**Issue by janaRicarda** [janaRicarda/emotion-tracker#79]
## Value proposition
As a user
I want to have a good working and pleasant looking app
In order to enjoy my time while using the app

## Acceptance criteria
- [ ] Everything works like before
- [ ] all UI-elements have to be consistent
- [ ] no UI-elements are overlapping
## Tasks
- [ ] Create and switch to branch feature/general-refinement
- [ ] add styling accordingly
