### ISSUE TITLE
create-tension-entry

### ISSUE THREAD

**Issue by ladydarkja** [janaRicarda/emotion-tracker#8]
## Value proposition
As a user
I want to record the intensity of my subjectively felt tension
So that I can accurately track the fluctuations in my level of tension over time.
## Description

![Image](https://github.com/janaRicarda/emotion-tracker/assets/115214197/81a76c48-0808-4851-b3c6-95087dca4fe9)

## Acceptance criteria
- [ ] The user can record their currently felt inner tension-level on a Scale from 0 to 100%.
- [ ] From there on, the User can decide, whether to only save their tension level ("Save" ).

## Tasks
- [ ] Create and switch to the feature branch `feature/create-emotion-entry`.
- [ ] Design and implement a slider or input field for recording tension levels to select their tension level on a scale from 0 to 100%.  Implement functionality accordingly.

**Comment by FelineHuhn** [comment]
I love that feature! 😍 The only thing: With the current wireframe and acceptance criteria, I can't understand how the feature is implemented. On which page will this implemented? How does the user get there? This feature needs a more detailed Description/Wireframe and acceptance criteria.

**Comment by FelineHuhn** [comment]
Well done team, this is now a well thought out user story 🥳🥳

I'll give you the green tick right now. 🚀🚀 But there's one more thing you should add to your acceptance criteria for what you already formulated the task "Display each entry with date, time and tensionlevel as a list below the form."

In the acceptance criteria you could add this feature part e.g. like: 
- the new created tension level entry shows up in a list below the form
- the entry is displayed with it's timestamp (date and time) and tension level 
- the tension level list is sorted by the timestamp with the latest below (or top? in the wireframe it's seems like below...)
