### ISSUE TITLE
emotion-records

### ISSUE THREAD

**Issue by Xristof23** [janaRicarda/emotion-tracker#9]
## Value proposition
As a user
I want to see an overview of my recorded emotion entries
In order to reflect on my past emotions.

## Description

![Image](https://github.com/janaRicarda/emotion-tracker/assets/152087206/3ad5d750-afb2-4f67-8b05-4092f4803201)

## Acceptance criteria
- [ ] Users can view the list of emotion entries by clicking on a button on the main page, each entry showing date and time
- [ ] If more details are available, Users can view the details of an entry by clicking on it
- [ ] Navigation to the other pages is possible via two buttons on the bottom of the page, named "The 7 basic emotions" and
      "Emotion Records"

## Tasks
- [ ] Create and switch to a new feature branch `feature/emotion-records`
- [ ] Move the list of emotion entries from `index.js`to newly created `pages/emotion-records.js`
- [ ] Add functionality to the list to show all available data of an entry on clicking the respective `li`-item
- [ ] Add navigation buttons below list of emotion entries
- [ ] Add Button  `Index.js` with `Link` to `pages/emotion-records.js`
- [ ] Add minimal styling to new elements

**Comment by FelineHuhn** [comment]
Good work team, everything clear formulated in a good structure 🥳 

I would to suggest to split this user story into two: As your value proposition is mentioning the benefit "I want to see an overview of my recorded emotion entries", a details view should not be another benefit, or? The details view of every tension level could be an own user story instead. 

One question: You implement buttons here and not a application-wide navigation, or? A button to navigate to the emotion records page, when the user is on the emotion records page doesn't make much sense... Also the user cannot navigate back to the main page from the emotion records page, but only to the seven emotions page, or? Better think about again, on which page you need which button (and which not). After that you need to adapt the tasks accordingly. 

Another point is, since you already have an overview of the tension levels in the user story before, the value proposition should emphasize that it should be shown on a separate page for clarity (or something similar to it, because the overview list is already visible before). 

Keep up the great work 🚀

**Comment by FelineHuhn** [comment]
Great improvement of the value proposition and also the button issue 👏👏

Ahhh now I understand, the tension level is only shown on button click on the date&time entry, yes? Maybe you should implement a toggle functionality, so that the user can click it away again, or? The way it is described now, the details are only displayed and then remain displayed. When it should be toggled, you can leave the wireframe as it is and just add it in the acceptance criteria and formulate a task for it. 

In tasks I noticed something new: Since others, which are not team members of your capstone project, will review your user stories, code etc. it would be more understandable to rename your "list" (as you call it in the tasks and also "list page" in the acceptance criteria) to something like emotion records list. And maybe think about to create a `EmotionRecordsList` component to render your "list", or did you plan it and not list it here?

**Comment by FelineHuhn** [comment]
Ready to work on 🚀🚀
